---
title: Класс Exception и его свойства
ms.date: 03/30/2017
ms.technology: dotnet-standard
helpviewer_keywords:
- exceptions, Exception class
- Exception class
ms.assetid: e2e1f8c4-e7b4-467d-9a66-13c90861221d
author: mairaw
ms.author: mairaw
ms.openlocfilehash: e17fa07fe2dd19cdcd03bc923940abfef886219c
ms.sourcegitcommit: 17ee6605e01ef32506f8fdc686954244ba6911de
ms.translationtype: HT
ms.contentlocale: ru-RU
ms.lasthandoff: 11/21/2019
ms.locfileid: "74283126"
---
# <a name="exception-class-and-properties"></a><span data-ttu-id="e1118-102">Класс и свойства исключений</span><span class="sxs-lookup"><span data-stu-id="e1118-102">Exception class and properties</span></span>

<span data-ttu-id="e1118-103"><xref:System.Exception> — это базовый класс, от которого наследуются исключения.</span><span class="sxs-lookup"><span data-stu-id="e1118-103">The <xref:System.Exception> class is the base class from which exceptions inherit.</span></span> <span data-ttu-id="e1118-104">Например, иерархия класса <xref:System.InvalidCastException> имеет следующий вид:</span><span class="sxs-lookup"><span data-stu-id="e1118-104">For example, the <xref:System.InvalidCastException> class hierarchy is as follows:</span></span>

<xref:System.Object>\
&nbsp;&nbsp;<xref:System.Exception>\
&nbsp;&nbsp;&nbsp;&nbsp;<xref:System.SystemException>\
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<xref:System.InvalidCastException>

<span data-ttu-id="e1118-105">Класс <xref:System.Exception> имеет следующие свойства, которые облегчают анализ исключения.</span><span class="sxs-lookup"><span data-stu-id="e1118-105">The <xref:System.Exception> class has the following properties that help make understanding an exception easier.</span></span>

| <span data-ttu-id="e1118-106">Имя свойства</span><span class="sxs-lookup"><span data-stu-id="e1118-106">Property Name</span></span> | <span data-ttu-id="e1118-107">ОПИСАНИЕ</span><span class="sxs-lookup"><span data-stu-id="e1118-107">Description</span></span> |
| ------------- | ----------- |
| <xref:System.Exception.Data> | <span data-ttu-id="e1118-108">Свойство <xref:System.Collections.IDictionary>, которое содержит произвольные данные в парах "ключ–значение".</span><span class="sxs-lookup"><span data-stu-id="e1118-108">An <xref:System.Collections.IDictionary> that holds arbitrary data in key-value pairs.</span></span> |
| <xref:System.Exception.HelpLink> | <span data-ttu-id="e1118-109">Может содержать URL-адрес (или URN) файла справки, который предоставляет подробные сведения о причине возникновения исключения.</span><span class="sxs-lookup"><span data-stu-id="e1118-109">Can hold a URL (or URN) to a help file that provides extensive information about the cause of an exception.</span></span> |
| <xref:System.Exception.InnerException> | <span data-ttu-id="e1118-110">Это свойство может использоваться для создания и сохранения последовательностей исключений во время обработки исключений.</span><span class="sxs-lookup"><span data-stu-id="e1118-110">This property can be used to create and preserve a series of exceptions during exception handling.</span></span> <span data-ttu-id="e1118-111">Его можно использовать для создания нового исключения, содержащего ранее перехваченные исключения.</span><span class="sxs-lookup"><span data-stu-id="e1118-111">You can use it to create a new exception that contains previously caught exceptions.</span></span> <span data-ttu-id="e1118-112">Исходное исключение может быть перехвачено вторым исключением в свойстве <xref:System.Exception.InnerException>, что позволяет коду, обрабатывающему второе исключение, проверить дополнительные данные.</span><span class="sxs-lookup"><span data-stu-id="e1118-112">The original exception can be captured by the second exception in the <xref:System.Exception.InnerException> property, allowing code that handles the second exception to examine the additional information.</span></span> <span data-ttu-id="e1118-113">Например, предположим, что у вас есть метод, который принимает аргумент в неправильном формате.</span><span class="sxs-lookup"><span data-stu-id="e1118-113">For example, suppose you have a method that receives an argument that's improperly formatted.</span></span>  <span data-ttu-id="e1118-114">Код пытается считать аргумент, но создается исключение.</span><span class="sxs-lookup"><span data-stu-id="e1118-114">The code tries to read the argument, but an exception is thrown.</span></span> <span data-ttu-id="e1118-115">Метод перехватывает исключение и выдает <xref:System.FormatException>.</span><span class="sxs-lookup"><span data-stu-id="e1118-115">The method catches the exception and throws a <xref:System.FormatException>.</span></span> <span data-ttu-id="e1118-116">Чтобы расширить возможности вызывающего объекта для определения причины исключения, иногда желательно, чтобы метод перехватывал исключение, выданное вспомогательной процедурой, а затем выдавал исключение, содержащее больше сведений о возникшей ошибке.</span><span class="sxs-lookup"><span data-stu-id="e1118-116">To improve the caller's ability to determine the reason an exception is thrown, it is sometimes desirable for a method to catch an exception thrown by a helper routine and then throw an exception more indicative of the error that has occurred.</span></span> <span data-ttu-id="e1118-117">Можно создать новое и более информативное исключение, где ссылка на внутреннее исключение может указывать на исходное исключение.</span><span class="sxs-lookup"><span data-stu-id="e1118-117">A new and more meaningful exception can be created, where the inner exception reference can be set to the original exception.</span></span> <span data-ttu-id="e1118-118">Затем это более информативное исключение может выдаваться вызывающему объекту.</span><span class="sxs-lookup"><span data-stu-id="e1118-118">This more meaningful exception can then be thrown to the caller.</span></span> <span data-ttu-id="e1118-119">Обратите внимание, что с помощью данной функции можно создать последовательность связанных исключений, которая завершается первым выданным исключением.</span><span class="sxs-lookup"><span data-stu-id="e1118-119">Note that with this functionality, you can create a series of linked exceptions that ends with the exception that was thrown first.</span></span> |
| <xref:System.Exception.Message> | <span data-ttu-id="e1118-120">Предоставляет сведения о причине возникновения исключения.</span><span class="sxs-lookup"><span data-stu-id="e1118-120">Provides details about the cause of an exception.</span></span>
| <xref:System.Exception.Source> | <span data-ttu-id="e1118-121">Возвращает или задает имя приложения или объекта, вызывавшего ошибку.</span><span class="sxs-lookup"><span data-stu-id="e1118-121">Gets or sets the name of the application or the object that causes the error.</span></span> |
| <xref:System.Exception.StackTrace>| <span data-ttu-id="e1118-122">Содержит трассировку стека, которую можно использовать для определения места возникновения ошибки.</span><span class="sxs-lookup"><span data-stu-id="e1118-122">Contains a stack trace that can be used to determine where an error occurred.</span></span> <span data-ttu-id="e1118-123">Эта трассировка стека содержит имя исходного файла и, при наличии отладочной информации, номер программной строки.</span><span class="sxs-lookup"><span data-stu-id="e1118-123">The stack trace includes the source file name and program line number if debugging information is available.</span></span> |

<span data-ttu-id="e1118-124">Большинство классов, унаследованных от <xref:System.Exception>, не реализуют дополнительные элементы и не предоставляют дополнительные функции. Они просто наследуются от <xref:System.Exception>.</span><span class="sxs-lookup"><span data-stu-id="e1118-124">Most of the classes that inherit from <xref:System.Exception> do not implement additional members or provide additional functionality; they simply inherit from <xref:System.Exception>.</span></span> <span data-ttu-id="e1118-125">Таким образом, наиболее важные сведения для исключения можно найти в иерархии классов исключений, имени исключения и информации, содержащейся в самом исключении.</span><span class="sxs-lookup"><span data-stu-id="e1118-125">Therefore, the most important information for an exception can be found in the hierarchy of exception classes, the exception name, and the information contained in the exception.</span></span>

<span data-ttu-id="e1118-126">Мы рекомендуем создавать и перехватывать только те объекты, которые являются производными от <xref:System.Exception>, но в качестве исключения можно создать любой объект, производный от класса <xref:System.Object>.</span><span class="sxs-lookup"><span data-stu-id="e1118-126">We recommend that you throw and catch only objects that derive from <xref:System.Exception>, but you can throw any object that derives from the <xref:System.Object> class as an exception.</span></span> <span data-ttu-id="e1118-127">Обратите внимание, что не все языки поддерживают создание и перехват объектов, не являющихся производными от <xref:System.Exception>.</span><span class="sxs-lookup"><span data-stu-id="e1118-127">Note that not all languages support throwing and catching objects that do not derive from <xref:System.Exception>.</span></span>
  
## <a name="see-also"></a><span data-ttu-id="e1118-128">См. также</span><span class="sxs-lookup"><span data-stu-id="e1118-128">See also</span></span>

- [<span data-ttu-id="e1118-129">Исключения</span><span class="sxs-lookup"><span data-stu-id="e1118-129">Exceptions</span></span>](index.md)
